FROM python:3.12-slim-bookworm

WORKDIR /build

RUN apt-get update && apt-get install -y --no-install-recommends \
    binutils \
    dpkg-dev \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml ./
COPY src ./src

RUN pip install --no-cache-dir -e ".[dev]" pyinstaller

RUN pyinstaller --onefile --name r42-cliniclink --distpath /build/dist $(which r42-cliniclink) && \
    pyinstaller --onefile --name r42-observe --distpath /build/dist $(which r42-observe)
